on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Send GitHub Actions metrics to DataDog
        uses: int128/datadog-actions-metrics@ac8d665371ebd5cf14f6c0e0224af8474b0a15cc # v1.57.0
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
          datadog-site: ddog-gov.com
